# — — — — —  — — — — — — — — — — — — — — — — — — #
#                   First Query                  
# — — — — —  — — — — — — — — — — — — — — — — — — #

[[Query]]
CsvPath = "./data/itemResults.csv"
HdrNames = []
IncColMode = false
Name = "Query 1"
OutCsvPath = "./out/itemResults_out.csv"
RelaOfCond = "&"

[[Query.Cond]]
Header = "School"
RelaOfItemValue = "="
Value = "21221"
ValueType = "string"

# — — — — —  — — — — — — — — — — — — — — — — — — #
#                   Second Query                  
# — — — — —  — — — — — — — — — — — — — — — — — — #

[[Query]]
CsvPath = "./data/itemResults1.csv"
HdrNames = ["School", "Item Response"]
IncColMode = false
Name = "Query 2"
OutCsvPath = "./out/itemResults1_out.csv"
RelaOfCond = "&"

[[Query.Cond]]
Header = "Domain"
RelaOfItemValue = "!="
Value = "Reading"
ValueType = "string"

[[Query.Cond]]
Header = "YrLevel"
RelaOfItemValue = "<"
Value = 9
ValueType = "int"
